Added the possibility to get colors
Frontify/app-bridge pull request #10
Opened 2021-08-06 07:17 UTC by oliverschwendener

Title says it all ;)

2021-08-06 14:19 UTC, SamuelAlev commented on src/AppBridgeNative.ts
> +        );
I would do it using `fetch` like [here](https://github.com/Frontify/app-bridge/blob/196310b84baba7acc9e7e63dce9fc96ee847d432/src/AppBridgeNative.ts#L55)

2021-08-06 14:19 UTC, SamuelAlev commented on src/AppBridgeNative.ts
> +        );
Same here

2021-08-06 14:25 UTC, SamuelAlev commented on src/AppBridgeNative.ts
> +        return response.palettes.reduce((previous, current): Color[] => previous.concat(current.colors), <Color[]>[]);
```suggestion
        return response.palettes.map((palette) => palette.colors).flat(1);
```

2021-08-06 14:28 UTC, SamuelAlev commented on src/window.d.ts
> +                };
If we use `fetch` this is then not needed

2021-08-06 14:29 UTC, SamuelAlev requested changes
Feature wise works fine but maybe a point worth to invest in

2021-08-13 10:58 UTC, oliverschwendener commented on src/AppBridgeNative.ts
> +        );
Done.

2021-08-13 11:02 UTC, oliverschwendener commented on src/AppBridgeNative.ts
> +        return response.palettes.reduce((previous, current): Color[] => previous.concat(current.colors), <Color[]>[]);
This is apparently an ES2019 feature, so I'll leave it as it is. We can refactor this as soon as we add "ES2019" to the "lib" option in `tsconfig.json`.

2021-08-13 11:02 UTC, oliverschwendener commented on src/window.d.ts
> +                };
Removed.

2021-08-13 11:02 UTC, oliverschwendener commented
As I have adressed all the important things you pointed out in the code review, I'll merge this now.

2021-08-13 11:03 UTC, merged