feat: create cover page repository and hook
Frontify/app-bridge pull request #231
Opened 2022-10-05 22:31 UTC by leko91

Cover page repository and hooks for usage in navigation manager.

CC: @SamuelAlev for vis

2022-10-06 06:23 UTC, oliverschwendener commented on src/AppBridgeTheme.spec.ts
> +        expect(appBridge.getProjectId()).toBe(HUB_ID);
Shouldn't this be `getHubId()`?

```suggestion
        expect(appBridge.getHubId()).toBe(HUB_ID);
```

2022-10-06 06:34 UTC, oliverschwendener commented on src/types/CoverPage.ts
> +    id: number;
We have to be careful with the property `id`. We don't have an entity `CoverPage` in the backend as only **one** cover page can be enabled/disabled per guideline. Therefore this property `id` could be misleading as someone could think that this is the cover page id, where in reality it is the portal id (aka guideline id).

I suggest removing it from this type, we don't use it so far right?

2022-10-06 07:16 UTC, oliverschwendener requested changes
See my comments.

2022-10-06 08:24 UTC, leko91 commented on src/types/CoverPage.ts
> +    id: number;
It makes sense, I just copied all the properties, I don't also see a need for an `id`

2022-10-06 13:55 UTC, oliverschwendener approved these changes
Code-wise this looks good to me.

Regarding the failing quality gate: either we test the remaining files or we see that this get's merged by a repository admin. @SamuelAlev

2022-10-10 07:45 UTC, SamuelAlev commented on src/AppBridgeTheme.spec.ts
> +        const appBridge = new AppBridgeTheme(HUB_ID);
The constructor here takes the project id

2022-10-10 07:45 UTC, SamuelAlev commented on src/react/useCoverPage.ts
> +/* (c) Copyright Frontify Ltd., all rights reserved. */
Missing a spec file to this hook

2022-10-10 07:46 UTC, SamuelAlev commented on src/react/useCoverPage.ts
> +import { CoverPage } from '../types';
```suggestion
import type { CoverPage } from '../types';
```

2022-10-10 08:21 UTC, oliverschwendener commented on src/AppBridgeTheme.spec.ts
> +        const appBridge = new AppBridgeTheme(HUB_ID);
Done.

2022-10-10 08:23 UTC, merged

2022-10-10 08:25 UTC, oliverschwendener commented
FYI: @SamuelAlev will take care of testing the react hooks later.